from pyspark.sql import SparkSession
from pyspark.sql.functions import *
from pyspark.sql.types import *
import argparse
from datetime import datetime

# Creating SparkSession
spark = SparkSession.builder.master("yarn").config("spark.sql.crossJoin.enabled", "true").enableHiveSupport().getOrCreate()
spark.sparkContext.setLogLevel("ERROR")
spark.conf.set("hive.exec.dynamic.partition.mode","nonstrict")

db='rtd_mart'

tbl_dim_year_month='dim_year_month'
tbl_fct_corep_crd4='fct_corep_crd4'
tbl_trs_agg_corep_crd4 ='trs_agg_corep_crd4'
tbl_etl_parameter='etl_parameter'

def proc_transform_agg_corep_crd4(p_run_rk=-1, p_data_set='A'):
    v_reporting_date=get_reporting_date()
    print(v_reporting_date)
    
    rYear_Month_RK=get_year_month_rk(v_reporting_date)
    print(rYear_Month_RK)
    
    v_run_rk=p_run_rk
           
    insert_trs_agg_corep_crd4(v_run_rk,p_data_set,rYear_Month_RK)
	
	
def get_reporting_date():
    query=f'''SELECT to_date(from_unixtime(unix_timestamp(parameter_value,"dd-MMM-yyyy")))  as reporting_date
    FROM {db}.{tbl_etl_parameter}  WHERE PARAMETER_NAME = 'REPORTING_DATE' '''
    
    reporting_date = spark.sql(query).collect()[0][0]
    return reporting_date
	
	
def get_year_month_rk(v_reporting_date):
    query=f'''SELECT YEAR_MONTH_RK FROM {db}.{tbl_dim_year_month} WHERE YEAR = year('{v_reporting_date}')
                   and MONTH= month('{v_reporting_date}') '''
    year_month_rk= spark.sql(query).collect()[0][0]
    return year_month_rk
	

def select_fct_corep_crd4_data(v_run_rk,p_data_set,rYear_Month_RK):
    query=f'''SELECT FCT.YEAR_MONTH_RK as YEAR_MONTH_RK, FCT.RRU_RK as  RRU_RK, FCT.LE_COUNTERPARTY_RK as  LE_COUNTERPARTY_RK, FCT.DIVISION_RK  as DIVISION_RK,
FCT.COREP_PRODUCT_CATEGORY_RK     as COREP_PRODUCT_CATEGORY_RK,
FCT.PRODUCT_RK  as PRODUCT_RK,
FCT.COREP_STD_ASSET_CLASS_RK   as COREP_STD_ASSET_CLASS_RK,
FCT.COREP_PRDEF_STD_ASSET_CLASS_RK   as  COREP_PRDEF_STD_ASSET_CLASS_RK,
FCT.B2_STD_ASSET_CLASS_RK as  B2_STD_ASSET_CLASS_RK,
FCT.COUNTERPARTY_MGS_PD_BAND_RK     as COUNTERPARTY_MGS_PD_BAND_RK,
FCT.UNSETTLED_PERIOD_CODE  as UNSETTLED_PERIOD_CODE, FCT.UNSETTLED_FACTOR_CODE  as UNSETTLED_FACTOR_CODE, FCT.CBI_PD_BAND_CODE_RK  as CBI_PD_BAND_CODE_RK, FCT.INCORP_COUNTRY_RK  as INCORP_COUNTRY_RK, FCT.BRANCH_COUNTRY_RK  as BRANCH_COUNTRY_RK, FCT.OP_COUNTRY_RK  as OP_COUNTRY_RK, FCT.RISK_COUNTRY_RK  as RISK_COUNTRY_RK, FCT.MGS_PD_BAND_CODE_RK  as MGS_PD_BAND_CODE_RK,
{v_run_rk}  as RUN_RK                             ,
'{p_data_set}' ADJUST_FLAG,
FCT.REPORTING_REGULATOR_CODE      as REPORTING_REGULATOR_CODE,
FCT.BASEL_DATA_FLAG as  BASEL_DATA_FLAG, FCT.RWA_APPROACH_CODE as  RWA_APPROACH_CODE, FCT.ACLM_PRODUCT_TYPE as  ACLM_PRODUCT_TYPE,
FCT.RETAIL_OFF_BAL_SHEET_FLAG    as RETAIL_OFF_BAL_SHEET_FLAG,
FCT.DEFAULT_FUND_CONTRIB_INDICATOR    as DEFAULT_FUND_CONTRIB_INDICATOR,
FCT.FLOW_TYPE  as FLOW_TYPE           ,
FCT.SME_FLAG  as SME_FLAG,
FCT.INTERNAL_TRANSACTION_FLAG   as INTERNAL_TRANSACTION_FLAG,
FCT.IRB_RISK_WEIGHT_RATIO  as IRB_RISK_WEIGHT_RATIO, FCT.STD_RISK_WEIGHT_RATIO  as STD_RISK_WEIGHT_RATIO,
FCT.B2_STD_RISK_WEIGHT_INDICATOR   as B2_STD_RISK_WEIGHT_INDICATOR,
FCT.SLOTTING_RESIDUAL_MATURITY    as SLOTTING_RESIDUAL_MATURITY,
FCT.RWA_CALC_METHOD  as RWA_CALC_METHOD, FCT.LRFE_UFE_FLAG  as LRFE_UFE_FLAG, FCT.OBLIGOR_TYPE  as OBLIGOR_TYPE, FCT.QCCP_FLAG  as QCCP_FLAG, FCT.DOUBLE_DEFAULT_FLAG  as DOUBLE_DEFAULT_FLAG, FCT.TRADING_BOOK_FLAG  as TRADING_BOOK_FLAG, FCT.REPORTING_TYPE_CODE as  REPORTING_TYPE_CODE, FCT.B3_CVA_CC_ADV_FLAG  as B3_CVA_CC_ADV_FLAG, FCT.B2_STD_CCF  as B2_STD_CCF, FCT.B2_STD_CCF_LESS_THAN_YEAR  as B2_STD_CCF_LESS_THAN_YEAR,
FCT.B2_STD_CCF_MORE_THAN_YEAR     as B2_STD_CCF_MORE_THAN_YEAR,
FCT.B2_IRB_OBSRVD_NEW_DEFAULT_FLAG  as B2_IRB_OBSRVD_NEW_DEFAULT_FLAG,
FCT.B2_STD_OBSRVD_NEW_DEFAULT_FLAG    as B2_STD_OBSRVD_NEW_DEFAULT_FLAG,
SUM (FCT.B2_IRB_ORIG_EXP_PRE_CON_FACTOR)   as B2_IRB_ORIG_EXP_PRE_CON_FACTOR,
SUM (FCT.IRB_ORIG_EXP_PRE_CONV_ONBAL)   as IRB_ORIG_EXP_PRE_CONV_ONBAL,
SUM (FCT.IRB_ORIG_EXP_PRE_CONV_OFBAL)      as IRB_ORIG_EXP_PRE_CONV_OFBAL,
SUM (FCT.B2_STD_ORIG_EXP_PRE_CON_FACTOR)  as  B2_STD_ORIG_EXP_PRE_CON_FACTOR, SUM (FCT.STD_ORIG_EXP_PRE_CONV_ONBAL)  as STD_ORIG_EXP_PRE_CONV_ONBAL,
SUM (FCT.STD_ORIG_EXP_PRE_CONV_OFBAL)    as STD_ORIG_EXP_PRE_CONV_OFBAL,
SUM (FCT.B3_CCP_MARGIN_INITL_CASH_AMT)    as  B3_CCP_MARGIN_INITL_CASH_AMT,
SUM (FCT.B3_CCP_MARGIN_INITL_NOCASH_AMT)    as B3_CCP_MARGIN_INITL_NOCASH_AMT,
SUM (FCT.B3_CVA_PROVISION_AMT)  as B3_CVA_PROVISION_AMT, SUM (FCT.B2_IRB_PROVISIONS_AMT) as  B2_IRB_PROVISIONS_AMT,
SUM (FCT.B2_STD_PROVISIONS_AMT)   as  B2_STD_PROVISIONS_AMT,
SUM (FCT.B2_STD_PROVISIONS_AMT_ONBAL)   as B2_STD_PROVISIONS_AMT_ONBAL,
SUM (FCT.B2_STD_PROVISIONS_AMT_OFBAL)    as  B2_STD_PROVISIONS_AMT_OFBAL,
SUM (FCT.B2_IRB_CRM_UFCP_GUAR_AMT)    as B2_IRB_CRM_UFCP_GUAR_AMT,
SUM (FCT.B2_IRB_CRM_UFCP_CRED_DERIV_AMT)   as B2_IRB_CRM_UFCP_CRED_DERIV_AMT,
SUM (FCT.B2_IRB_CRM_FCP_ELG_FIN_COL_AMT)    as  B2_IRB_CRM_FCP_ELG_FIN_COL_AMT,
SUM (FCT.B2_IRB_CRM_FCP_OTH_PHY_COL_AMT)  as B2_IRB_CRM_FCP_OTH_PHY_COL_AMT,
SUM (FCT.B2_IRB_CRM_FCP_OTH_FUNDED_AMT)    as B2_IRB_CRM_FCP_OTH_FUNDED_AMT,
SUM (FCT.B2_IRB_CRM_FCP_REAL_ESTATE_AMT)   as B2_IRB_CRM_FCP_REAL_ESTATE_AMT,
SUM (FCT.B2_IRB_CRM_FCP_RECEIVABLES_AMT)    as B2_IRB_CRM_FCP_RECEIVABLES_AMT,
SUM (FCT.B2_IRB_CRM_UFCP_DOUBLE_DEF_AMT)    as  B2_IRB_CRM_UFCP_DOUBLE_DEF_AMT,
SUM (FCT.B2_STD_EFF_GTEE_AMT) as  B2_STD_EFF_GTEE_AMT, SUM (FCT.B2_STD_EFF_CDS_AMT)  as B2_STD_EFF_CDS_AMT,
SUM (FCT.B2_STD_OTH_FUN_CRED_PROT_AMT)    as B2_STD_OTH_FUN_CRED_PROT_AMT,
SUM (FCT.B2_STD_EFF_FIN_COLL_AMT)  as B2_STD_EFF_FIN_COLL_AMT,
SUM (FCT.B2_STD_COLL_VOLATILITY_AMT) as   B2_STD_COLL_VOLATILITY_AMT,
SUM (FCT.B2_STD_COLL_MTY_MISMATCH_AMT) as  B2_STD_COLL_MTY_MISMATCH_AMT,
SUM (FCT.B2_IRB_NETTED_COLL_GBP)   as B2_IRB_NETTED_COLL_GBP,
SUM (FCT.B2_STD_NETTED_COLL_GBP)   as B2_STD_NETTED_COLL_GBP,
SUM (FCT.B2_STD_CRM_TOT_OUTFLOW)    as B2_STD_CRM_TOT_OUTFLOW,
SUM (FCT.B2_STD_CRM_TOT_OUTFLOW_ONBAL)   as B2_STD_CRM_TOT_OUTFLOW_ONBAL,
SUM (FCT.B2_STD_CRM_TOT_OUTFLOW_OFBAL)   as B2_STD_CRM_TOT_OUTFLOW_OFBAL,
SUM (FCT.B2_STD_CRM_TOT_INFLOW)       as B2_STD_CRM_TOT_INFLOW,
SUM (FCT.B2_STD_CRM_TOT_INFLOW_ONBAL)  as B2_STD_CRM_TOT_INFLOW_ONBAL,
SUM (FCT.B2_STD_CRM_TOT_INFLOW_OFBAL)   as B2_STD_CRM_TOT_INFLOW_OFBAL,
SUM (FCT.EAD_LGD_NUMERATOR)  as EAD_LGD_NUMERATOR, SUM (FCT.EAD_LGD_NUMERATOR_ON)  as EAD_LGD_NUMERATOR_ON, SUM (FCT.EAD_LGD_NUMERATOR_OFF)
    as EAD_LGD_NUMERATOR_OFF,
SUM (FCT.EAD_MAT_YEARS_NUMERATOR)
   as  EAD_MAT_YEARS_NUMERATOR,
SUM (FCT.EAD_MAT_YEARS_NUMERATOR_ON)
    as EAD_MAT_YEARS_NUMERATOR_ON,
SUM (FCT.EAD_MAT_YEARS_NUMERATOR_OFF)
    as EAD_MAT_YEARS_NUMERATOR_OFF,
SUM (FCT.EAD_PD_NUMERATOR)  as EAD_PD_NUMERATOR, SUM (FCT.EAD_PD_NUMERATOR_ON)  as EAD_PD_NUMERATOR_ON, SUM (FCT.EAD_PD_NUMERATOR_OFF) as  EAD_PD_NUMERATOR_OFF, SUM (FCT.EAD_POST_CRM_AMT)  as EAD_POST_CRM_AMT, SUM (FCT.B2_IRB_EAD_AMT_ONBAL)  as B2_IRB_EAD_AMT_ONBAL, SUM (FCT.B2_IRB_EAD_AMT_OFBAL)  as B2_IRB_EAD_AMT_OFBAL, SUM (FCT.B2_APP_EXPECTED_LOSS_AMT)
   as  B2_APP_EXPECTED_LOSS_AMT,
SUM (FCT.B2_IRB_EL_AMT_ONBAL)  as B2_IRB_EL_AMT_ONBAL, SUM (FCT.B2_IRB_EL_AMT_OFBAL)  as B2_IRB_EL_AMT_OFBAL, SUM (FCT.RWA_POST_CRM_AMOUNT) as  RWA_POST_CRM_AMOUNT, SUM (FCT.B2_IRB_RWA_AMT_ONBAL)  as B2_IRB_RWA_AMT_ONBAL, SUM (FCT.B2_IRB_RWA_AMT_OFBAL)  as B2_IRB_RWA_AMT_OFBAL, SUM (FCT.B3_CCP_MARGIN_INITL_RWA_AMT)
    as B3_CCP_MARGIN_INITL_RWA_AMT,
SUM (FCT.B3_CCP_MARGIN_NONINITL_RWA_AMT)
    as B3_CCP_MARGIN_NONINITL_RWA_AMT,
SUM (FCT.B1_RWA_POST_CRM_AMT)  as B1_RWA_POST_CRM_AMT, CASE
   WHEN FCT.OBLIGOR_TYPE = 'CORP'
   THEN
      COUNT (DISTINCT FCT.COUNTERPARTY_RK)
   ELSE
      0
END
    as CORP_OBLIGOR_COUNT,
SUM (
   CASE
      WHEN FCT.OBLIGOR_TYPE = 'RETAIL'
      THEN
         FCT.RETAIL_OBLIGOR_COUNT
      ELSE
         0
   END)
    as RETAIL_OBLIGOR_COUNT,
SUM (FCT.UNSETTLED_AMOUNT)  as UNSETTLED_AMOUNT, SUM (FCT.UNSETTLED_PRICE_DIFFERENCE_AMT)  as UNSETTLED_PRICE_DIFFERENCE_AMT, SUM (FCT.B3_CVA_CC_ADV_VAR_AVG)  as B3_CVA_CC_ADV_VAR_AVG, SUM (FCT.B3_CVA_CC_ADV_VAR_SPOT) as B3_CVA_CC_ADV_VAR_SPOT, NULL  as B3_CVA_CC_ADV_VAR_USED,
SUM (FCT.B3_CVA_CC_ADV_VAR_STRESS_AVG)   as B3_CVA_CC_ADV_VAR_STRESS_AVG,
SUM (FCT.B3_CVA_CC_ADV_VAR_STRESS_SPOT)      as B3_CVA_CC_ADV_VAR_STRESS_SPOT, 
 NULL  as B3_CVA_CC_ADV_VAR_STRESS_USED,  NULL  as B3_CVA_CC_CREDIT_SPREAD_MEAN,  SUM (FCT.B3_CVA_CC_CD_SNGL_NAM_NTNL_AMT)
     as B3_CVA_CC_CDS_SNGL_NM_NTNL_AMT,
 SUM (FCT.B3_CVA_CC_CDS_INDEX_NTNL_AMT)
    as  B3_CVA_CC_CDS_INDEX_NTNL_AMT,
 SUM (FCT.B3_CVA_CC_CAPITAL_AMT)
     as B3_CVA_CC_CAPITAL_AMT,
SUM (FCT.B3_CVA_CC_RWA_AMT)  as B3_CVA_CC_RWA_AMT,
  SUM (FCT.B2_STD_NET_EXP_PRE_CRM_SUBST)
     as B2_STD_NET_EXP_PRE_CRM_SUBST,
 SUM (FCT.STD_NET_EXP_PRECRM_SUBST_ONBAL)
     as STD_NET_EXP_PRECRM_SUBST_ONBAL,
 SUM (FCT.STD_NET_EXP_PRECRM_SUBST_OFBAL)
     as STD_NET_EXP_PRECRM_SUBST_OFBAL,
 SUM (FCT.B2_STD_NET_EXP_POST_CRM_SUBST)
     as B2_STD_NET_EXP_POST_CRM_SUBST,
 SUM (FCT.STD_NET_EXP_POSTCRM_SUBT_ONBAL)
     as STD_NET_EXP_POSTCRM_SUBT_ONBAL,
 SUM (FCT.STD_NET_EXP_POSTCRM_SUBT_OFBAL)
     as STD_NET_EXP_POSTCRM_SUBT_OFBAL,
 SUM (FCT.B2_STD_FULLY_ADJ_EXP)  as B2_STD_FULLY_ADJ_EXP,  SUM (FCT.B2_STD_FULLY_ADJ_EXP_ONBAL)
     as B2_STD_FULLY_ADJ_EXP_ONBAL,
 SUM (FCT.B2_STD_FULLY_ADJ_EXP_OFBAL)
     as B2_STD_FULLY_ADJ_EXP_OFBAL,
 SUM (FCT.B2_STD_FULLY_ADJ_EXP_CCF_0)
     as B2_STD_FULLY_ADJ_EXP_CCF_0,
 SUM (FCT.B2_STD_FULLY_ADJ_EXP_CCF_20)
     as B2_STD_FULLY_ADJ_EXP_CCF_20,
 SUM (FCT.B2_STD_FULLY_ADJ_EXP_CCF_50)
     as B2_STD_FULLY_ADJ_EXP_CCF_50,
 SUM (FCT.B2_STD_FULLY_ADJ_EXP_CCF_100)
     as B2_STD_FULLY_ADJ_EXP_CCF_100,
 SUM (FCT.B2_STD_EXPOSURE_VALUE)
    as  B2_STD_EXPOSURE_VALUE,
 SUM (FCT.B2_STD_EXPOSURE_VALUE_ONBAL)
     as B2_STD_EXPOSURE_VALUE_ONBAL,
 SUM (FCT.B2_STD_EXPOSURE_VALUE_OFBAL)
    as  B2_STD_EXPOSURE_VALUE_OFBAL,
 SUM (FCT.B2_STD_EAD_POST_CRM_AMT_ONBAL)
     as B2_STD_EAD_POST_CRM_AMT_ONBAL,
 SUM (FCT.B2_STD_EAD_POST_CRM_AMT_OFBAL)
    as  B2_STD_EAD_POST_CRM_AMT_OFBAL,
 SUM (FCT.B2_STD_RWA_AMT)  as B2_STD_RWA_AMT,  SUM (FCT.B2_STD_RWA_AMT_ONBAL)  as B2_STD_RWA_AMT_ONBAL,  SUM (FCT.B2_STD_RWA_AMT_OFBAL) as  B2_STD_RWA_AMT_OFBAL,  SUM (FCT.B2_STD_RWA_POST_CRM_AMT_ONBAL)
     as B2_STD_RWA_POST_CRM_AMT_ONBAL,
 SUM (FCT.B2_STD_RWA_POST_CRM_AMT_OFBAL)
     as B2_STD_RWA_POST_CRM_AMT_OFBAL,
 SUM (FCT.B2_STD_CRM_TOT_OUTFLOW_RWA)
     as B2_STD_CRM_TOT_OUTFLOW_RWA,
 SUM (FCT.B2_STD_CRM_TOT_INFLOW_RWA)
     as B2_STD_CRM_TOT_INFLOW_RWA,
 SUM (FCT.IMP_WRITE_OFF_AMT) as  IMP_WRITE_OFF_AMT,  SUM (FCT.IMP_IMPAIRMENT_AMT)  as IMP_IMPAIRMENT_AMT,  SUM (FCT.B2_STD_COLL_FX_HAIRCUT_AMT)
     as B2_STD_COLL_FX_HAIRCUT_AMT,
 FCT.CRD4_REP_IRB_FLAG as  CRD4_REP_IRB_FLAG,  FCT.CRD4_REP_IRBEQ_FLAG as  CRD4_REP_IRBEQ_FLAG,  FCT.CRD4_REP_STD_FLAG as  CRD4_REP_STD_FLAG,  FCT.CRD4_REP_STDFLOW_FLAG as  CRD4_REP_STDFLOW_FLAG,  FCT.CRD4_REP_SETTL_FLAG  as CRD4_REP_SETTL_FLAG,  FCT.CRD4_REP_CVA_FLAG  as CRD4_REP_CVA_FLAG,  FCT.STD_EXP_TYPE_PRI_ORDER_RULE_RK
     as STD_EXP_TYPE_PRI_ORDER_RULE_RK,
 FCT.CRD4_SOV_SUBSTITUTION_FLAG
     as CRD4_SOV_SUBSTITUTION_FLAG,
 FCT.STD_RW_PRIORITY_ORDER_RULE_RK
     as STD_RW_PRIORITY_ORDER_RULE_RK,
 FCT.UNLIKELY_PAY_FLAG  as UNLIKELY_PAY_FLAG,  FCT.RISK_ON_RRU_RK  as RISK_ON_RRU_RK,  SUM (FCT.B2_STD_EXP_HAIRCUT_ADJ_AMT)
    as  B2_STD_EXP_HAIRCUT_ADJ_AMT,
 FCT.COUNTERPARTY_RK  as COUNTERPARTY_RK,  FCT.STD_EXPOSURE_DEFAULT_FLAG
     as STD_EXPOSURE_DEFAULT_FLAG,
 FCT.CRD4_STD_RP_SME_FLAG  as CRD4_STD_RP_SME_FLAG,  FCT.CRD4_IRB_RP_SME_FLAG as  CRD4_IRB_RP_SME_FLAG,  FCT.STD_SME_DISCOUNT_APP_FLAG
     as STD_SME_DISCOUNT_APP_FLAG,
 FCT.IRB_SME_DISCOUNT_APP_FLAG
     as IRB_SME_DISCOUNT_APP_FLAG,
 FCT.TRANSITIONAL_PORTFOLIO_FLAG
     as TRANSITIONAL_PORTFOLIO_FLAG,
 FCT.SLOTTING_EFF_MATURITY_BAND_RK
     as SLOTTING_EFF_MATURITY_BAND_RK    ,
 FCT.COREP_IRB_ASSET_CLASS_RK
    as  COREP_IRB_ASSET_CLASS_RK,
 FCT.COREP_CRM_REPORTING_FLAG
     as COREP_CRM_REPORTING_FLAG,
 SUM (FCT.ALTERNATIVE_STD_CCF_0)
     as ALTERNATIVE_STD_CCF_0,
 SUM (FCT.ALTERNATIVE_STD_CCF_20)
    as  ALTERNATIVE_STD_CCF_20,
 SUM (FCT.ALTERNATIVE_STD_CCF_50)
    as  ALTERNATIVE_STD_CCF_50,
 SUM (FCT.ALTERNATIVE_STD_CCF_100)
    as  ALTERNATIVE_STD_CCF_100,
 SUM (FCT.COLL_GOOD_PROV_AMT)  as COLL_GOOD_PROV_AMT,  FCT.B2_IRB_INTEREST_AT_DEFAULT_GBP, 
 FCT.PERS_ACC_FLAG,                          
 FCT.B3_SME_RP_FLAG,                        
 FCT.B3_SME_DISCOUNT_FLAG ,   
SUM (FCT.STATUTORY_LEDGER_BALANCE)
as STATUTORY_LEDGER_BALANCE ,
SUM (FCT.CARRYING_VALUE)  as CARRYING_VALUE , SUM (FCT.LEVERAGE_EXPOSURE)  as LEVERAGE_EXPOSURE, FCT.P3_PD_BAND_RK  as P3_PD_BAND_RK, SUM (FCT.EXP_SECURED_BY_COLLATERAL_AMT)
    as EXP_SECURED_BY_COLLATERAL_AMT,
SUM (FCT.EXP_SEC_BY_COLL_COVERED_AMT)
    as EXP_SEC_BY_COLL_COVERED_AMT,
SUM (FCT.EXP_SECURED_BY_GUARANTEES_AMT)
    as EXP_SECURED_BY_GUARANTEES_AMT,
SUM (FCT.EXP_SEC_BY_GUAR_COVERED_AMT)
    as EXP_SEC_BY_GUAR_COVERED_AMT,
SUM (FCT.EXP_SECURED_BY_CRD_DRVS_AMT)
    as EXP_SECURED_BY_CRD_DRVS_AMT,
SUM (FCT.EXP_SEC_BY_CRD_DRV_COVERED_AMT)
   as  EXP_SEC_BY_CRD_DRV_COVERED_AMT,
FCT.P3_STD_ASSET_CLASS_RK  as P3_STD_ASSET_CLASS_RK, SUM (FCT.BLANK_CRM_CATEGORY_AMT)
    as BLANK_CRM_CATEGORY_AMT,
SUM (FCT.EXP_UNSECURED_CARRYING_AMT)
    as EXP_UNSECURED_CARRYING_AMT,
FCT.CRD4_MEMO_ITEMS_ASSET_CLASS_RK 
    as CRD4_MEMO_ITEMS_ASSET_CLASS_RK,
SUM (FCT.INTEREST_SUSPENSE_AMT_GBP)
    as INTEREST_SUSPENSE_AMT_GBP,
SUM (FCT.TOT_REGU_PROV_AMT_GBP)
    as TOT_REGU_PROV_AMT_GBP,
FCT.COREP_INCORP_COUNTRY_RK   as  COREP_INCORP_COUNTRY_RK,
SUM (FCT.NET_MKT_VAL)  as NET_MKT_VAL,
SUM (FCT.B2_APP_CAP_REQ_POST_CRM_AMT)
    as B2_APP_CAP_REQ_POST_CRM_AMT,
FCT.LER_CHILD_COUNTERPARTY_RK 
    as LER_CHILD_COUNTERPARTY_RK,
FCT.IG_EXCLUSION_FLAG 
                     as  IG_EXCLUSION_FLAG,
fct.NEW_IN_DEFAULT_FLAG,      
FCT.WALKER_COST_CENTRE_RK  as WALKER_COST_CENTRE_RK, FCT.RETAIL_POOL_SME_FLAG  as  RETAIL_POOL_SME_FLAG, FCT.SYS_CODE SYS_CODE, FCT.CS_PROXY_USED_FLAG, FCT.MARKET_RISK_SUB_TYPE,
SUM(FCT.ACCRUED_INTEREST_GBP) as  ACCRUED_INTEREST_GBP,
SUM(FCT.ACCRUED_INT_ONBAL_AMT) as  ACCRUED_INT_ONBAL_AMT,
SUM(FCT.B2_IRB_RWA_PRE_CDS) as  B2_IRB_RWA_PRE_CDS, FCT.DEAL_TYPE,
SUM(FCT.DRAWN_LEDGER_BALANCE) as  DRAWN_LEDGER_BALANCE,
SUM(FCT.EAD_PRE_CRM_AMT)  as EAD_PRE_CRM_AMT,
SUM(FCT.GROSS_CARRYING_VALUE)  as GROSS_CARRYING_VALUE,
SUM(FCT.IMPAIRMENT_LOSS_GBP)  as IMPAIRMENT_LOSS_GBP,
SUM(FCT.OFF_BALANCE_EXPOSURE)  as OFF_BALANCE_EXPOSURE,
SUM(FCT.OFF_BAL_LED_EXP_GBP_POST_SEC) as  OFF_BAL_LED_EXP_GBP_POST_SEC,
SUM(FCT.ON_BALANCE_LEDGER_EXPOSURE) as  ON_BALANCE_LEDGER_EXPOSURE,
SUM(FCT.ON_BAL_LED_EXP_GBP_POST_SEC)  as ON_BAL_LED_EXP_GBP_POST_SEC,
SUM(FCT.PROVISION_AMOUNT_GBP)  as PROVISION_AMOUNT_GBP,
SUM(FCT.RA_AD_EXP)  as RA_AD_EXP,
SUM(FCT.UNDRAWN_COMMITMENT_AMT)  as UNDRAWN_COMMITMENT_AMT,
SUM(FCT.FSA_GROSS_EXPOSURE) as FSA_GROSS_EXPOSURE, FCT.FSA045_PD_BAND_RK, FCT.ULTIMATE_RING_FENCE_PARENT_RK,  
FCT.STS_SECURITISATION,      
FCT.STS_SEC_QUAL_CAP_TRTMNT, 
FCT.STS_SEC_APPROACH_CODE,   
SUM(FCT.B3_APP_RWA_INC_CVA_CC_AMT)  as B3_APP_RWA_INC_CVA_CC_AMT,
SUM(FCT.IFRS9_TOT_REGU_ECL_AMT_GBP)  as IFRS9_TOT_REGU_ECL_AMT_GBP,
SUM(FCT.IFRS9_FINAL_ECL_MES_GBP)  as IFRS9_FINAL_ECL_MES_GBP, FCT.IFRS9_FINAL_STAGE, FCT.IFRS9_STAGE_3_TYPE,
SUM(FCT.IFRS9_FINAL_IIS_GBP)  as IFRS9_FINAL_IIS_GBP,
SUM(FCT.IFRS9_PROV_IMPAIRMENT_AMT_GBP)  as IFRS9_PROV_IMPAIRMENT_AMT_GBP, FCT.IFRS9_ECL_CURRENCY_CODE,
SUM(FCT.IFRS9_PROV_WRITE_OFF_AMT_GBP)  as IFRS9_PROV_WRITE_OFF_AMT_GBP,
SUM(FCT.IFRS9_TOT_STATUT_ECL_AMT_GBP) as  IFRS9_TOT_STATUT_ECL_AMT_GBP,
SUM(FCT.IFRS9_DISCNT_UNWIND_AMT_GBP) as  IFRS9_DISCNT_UNWIND_AMT_GBP,
FCT.RISK_TYPE,          
SUM(FCT.NGAAP_PROVISION_AMT_GBP) as  NGAAP_PROVISION_AMT_GBP,   
SUM(FCT.REP_PROVISION_AMT_GBP)  as REP_PROVISION_AMT_GBP,      
FCT.REP_PROVISION_TYPE,        
FCT.C33_EXPOSURE_SECTOR,       
FCT.FINREP_COUNTERPARTY_SECTOR,
FCT.IAS39_CLASS,               
SUM(FCT.B2_STD_RWA_PRE_SPRT_AMT) as  B2_STD_RWA_PRE_SPRT_AMT,
SUM(FCT.B2_STD_RWA_PRE_SPRT_AMT_ONBAL) as  B2_STD_RWA_PRE_SPRT_AMT_ONBAL,
SUM(FCT.B2_STD_RWA_PRE_SPRT_AMT_OFBAL) as  B2_STD_RWA_PRE_SPRT_AMT_OFBAL,
SUM(FCT.RWA_POST_CRM_PRE_SPRT_AMOUNT) RWA_POST_CRM_PRE_SPRT_AMOUNT,
SUM(FCT.B2_IRB_RWA_PRE_SPRT_AMT_ONBAL) as  B2_IRB_RWA_PRE_SPRT_AMT_ONBAL,
SUM(FCT.B2_IRB_RWA_PRE_SPRT_AMT_OFBAL) as  B2_IRB_RWA_PRE_SPRT_AMT_OFBAL,
FCT.CRR2_501A_DISCOUNT_FLAG,   
FCT.MORTGAGES_FLAG,            
FCT.SECURITY_RK,               
SUM(FCT.B2_IRB_CRM_COD_AMT)  as B2_IRB_CRM_COD_AMT,
SUM(FCT.B2_IRB_CRM_LIP_AMT) as  B2_IRB_CRM_LIP_AMT, FCT.BASEL_SECURITY_SUB_TYPE, FCT.SYS_PROTECTION_TYPE FROM rtd_mart.FCT_COREP_CRD4 FCT WHERE  FCT.YEAR_MONTH_RK = '{rYear_Month_RK}' AND FCT.ADJUST_FLAG = '{p_data_set}' 
GROUP BY FCT.YEAR_MONTH_RK,
FCT.RRU_RK,
FCT.LE_COUNTERPARTY_RK,
FCT.DIVISION_RK,
FCT.COREP_PRODUCT_CATEGORY_RK,
FCT.PRODUCT_RK,
FCT.COREP_STD_ASSET_CLASS_RK,
FCT.COREP_PRDEF_STD_ASSET_CLASS_RK,
FCT.B2_STD_ASSET_CLASS_RK,
FCT.COUNTERPARTY_MGS_PD_BAND_RK,
FCT.UNSETTLED_PERIOD_CODE,
FCT.UNSETTLED_FACTOR_CODE,
FCT.CBI_PD_BAND_CODE_RK,
FCT.INCORP_COUNTRY_RK,
FCT.BRANCH_COUNTRY_RK,
FCT.OP_COUNTRY_RK,
FCT.RISK_COUNTRY_RK,
FCT.MGS_PD_BAND_CODE_RK,
FCT.RUN_RK,
FCT.ADJUST_FLAG,
FCT.REPORTING_REGULATOR_CODE,
FCT.BASEL_DATA_FLAG,
FCT.RWA_APPROACH_CODE,
FCT.ACLM_PRODUCT_TYPE,
FCT.RETAIL_OFF_BAL_SHEET_FLAG,
FCT.DEFAULT_FUND_CONTRIB_INDICATOR,
FCT.FLOW_TYPE ,
FCT.SME_FLAG,
FCT.INTERNAL_TRANSACTION_FLAG,
FCT.IRB_RISK_WEIGHT_RATIO,
FCT.STD_RISK_WEIGHT_RATIO,
FCT.B2_STD_RISK_WEIGHT_INDICATOR,
FCT.SLOTTING_RESIDUAL_MATURITY,
FCT.RWA_CALC_METHOD,
FCT.LRFE_UFE_FLAG,
FCT.OBLIGOR_TYPE,
FCT.QCCP_FLAG,
FCT.DOUBLE_DEFAULT_FLAG,
FCT.TRADING_BOOK_FLAG,
FCT.REPORTING_TYPE_CODE,
FCT.B3_CVA_CC_ADV_FLAG,
FCT.B2_STD_CCF,
FCT.B2_STD_CCF_LESS_THAN_YEAR,
FCT.B2_STD_CCF_MORE_THAN_YEAR,
FCT.B2_IRB_OBSRVD_NEW_DEFAULT_FLAG,
FCT.B2_STD_OBSRVD_NEW_DEFAULT_FLAG,
FCT.CRD4_REP_IRB_FLAG,
FCT.CRD4_REP_IRBEQ_FLAG,
FCT.CRD4_REP_STD_FLAG,
FCT.CRD4_REP_STDFLOW_FLAG,
FCT.CRD4_REP_SETTL_FLAG,
FCT.CRD4_REP_CVA_FLAG,
FCT.STD_EXP_TYPE_PRI_ORDER_RULE_RK,
FCT.CRD4_SOV_SUBSTITUTION_FLAG,
FCT.STD_RW_PRIORITY_ORDER_RULE_RK,
FCT.UNLIKELY_PAY_FLAG,
FCT.RISK_ON_RRU_RK,
FCT.COUNTERPARTY_RK,
FCT.STD_EXPOSURE_DEFAULT_FLAG,
FCT.CRD4_STD_RP_SME_FLAG,
FCT.CRD4_IRB_RP_SME_FLAG,
FCT.STD_SME_DISCOUNT_APP_FLAG,
FCT.IRB_SME_DISCOUNT_APP_FLAG,
FCT.TRANSITIONAL_PORTFOLIO_FLAG,
FCT.SLOTTING_EFF_MATURITY_BAND_RK ,
FCT.COREP_IRB_ASSET_CLASS_RK,
FCT.COREP_CRM_REPORTING_FLAG,
FCT.B2_IRB_INTEREST_AT_DEFAULT_GBP,
FCT.PERS_ACC_FLAG,                 
FCT.B3_SME_RP_FLAG,                
FCT.B3_SME_DISCOUNT_FLAG,          
FCT.P3_PD_BAND_RK,
FCT.P3_STD_ASSET_CLASS_RK,
FCT.CRD4_MEMO_ITEMS_ASSET_CLASS_RK,
FCT.COREP_INCORP_COUNTRY_RK,
FCT.LER_CHILD_COUNTERPARTY_RK,
FCT.IG_EXCLUSION_FLAG, 
FCT.NEW_IN_DEFAULT_FLAG,        
FCT.WALKER_COST_CENTRE_RK,      
FCT.RETAIL_POOL_SME_FLAG,      
FCT.SYS_CODE,   
FCT.CS_PROXY_USED_FLAG,
FCT.MARKET_RISK_SUB_TYPE,
FCT.DEAL_TYPE ,
FCT.FSA045_PD_BAND_RK,
FCT.ULTIMATE_RING_FENCE_PARENT_RK,  
FCT.STS_SECURITISATION,       
FCT.STS_SEC_QUAL_CAP_TRTMNT,  
FCT.STS_SEC_APPROACH_CODE,    
FCT.IFRS9_FINAL_STAGE,        
FCT.IFRS9_STAGE_3_TYPE,       
FCT.IFRS9_ECL_CURRENCY_CODE,  
FCT.RISK_TYPE,           
FCT.REP_PROVISION_TYPE,
FCT.C33_EXPOSURE_SECTOR,
FCT.FINREP_COUNTERPARTY_SECTOR, 
FCT.IAS39_CLASS,                
FCT.CRR2_501A_DISCOUNT_FLAG,    
FCT.MORTGAGES_FLAG,             
FCT.SECURITY_RK,                
FCT.BASEL_SECURITY_SUB_TYPE,
FCT.SYS_PROTECTION_TYPE'''
    
    df_select=spark.sql(query)
    return df_select
	

def insert_trs_agg_corep_crd4(v_run_rk,p_data_set,rYear_Month_RK):
    df_select=select_fct_corep_crd4_data(v_run_rk,p_data_set,rYear_Month_RK)
    df_select.createOrReplaceTempView("AGG1")
    
    insert_df=spark.sql(f'''INSERT INTO  rtd_mart.TRS_AGG_COREP_CRD4 
SELECT AGG1.YEAR_MONTH_RK YEAR_MONTH_RK,
AGG1.RRU_RK RRU_RK,
AGG1.LE_COUNTERPARTY_RK LE_COUNTERPARTY_RK,
AGG1.DIVISION_RK DIVISION_RK,
AGG1.COREP_PRODUCT_CATEGORY_RK COREP_PRODUCT_CATEGORY_RK,
AGG1.PRODUCT_RK PRODUCT_RK,
AGG1.COREP_STD_ASSET_CLASS_RK COREP_STD_ASSET_CLASS_RK,
AGG1.COREP_PRDEF_STD_ASSET_CLASS_RK
   COREP_PRDEF_STD_ASSET_CLASS_RK,
AGG1.B2_STD_ASSET_CLASS_RK B2_STD_ASSET_CLASS_RK,
AGG1.COUNTERPARTY_MGS_PD_BAND_RK COUNTERPARTY_MGS_PD_BAND_RK,
AGG1.UNSETTLED_PERIOD_CODE UNSETTLED_PERIOD_CODE,
AGG1.UNSETTLED_FACTOR_CODE UNSETTLED_FACTOR_CODE,
AGG1.CBI_PD_BAND_CODE_RK CBI_PD_BAND_CODE_RK,
AGG1.INCORP_COUNTRY_RK INCORP_COUNTRY_RK,
AGG1.BRANCH_COUNTRY_RK BRANCH_COUNTRY_RK,
AGG1.OP_COUNTRY_RK OP_COUNTRY_RK,
AGG1.RISK_COUNTRY_RK RISK_COUNTRY_RK,
AGG1.MGS_PD_BAND_CODE_RK MGS_PD_BAND_CODE_RK,
AGG1.RUN_RK RUN_RK,
AGG1.ADJUST_FLAG ADJUST_FLAG,
AGG1.REPORTING_REGULATOR_CODE REPORTING_REGULATOR_CODE,
AGG1.BASEL_DATA_FLAG BASEL_DATA_FLAG,
AGG1.RWA_APPROACH_CODE RWA_APPROACH_CODE,
AGG1.ACLM_PRODUCT_TYPE ACLM_PRODUCT_TYPE,
AGG1.RETAIL_OFF_BAL_SHEET_FLAG RETAIL_OFF_BAL_SHEET_FLAG,
AGG1.DEFAULT_FUND_CONTRIB_INDICATOR
DEFAULT_FUND_CONTRIB_INDICATOR,
AGG1.FLOW_TYPE FLOW_TYPE,
AGG1.SME_FLAG SME_FLAG,
AGG1.INTERNAL_TRANSACTION_FLAG INTERNAL_TRANSACTION_FLAG,
AGG1.IRB_RISK_WEIGHT_RATIO IRB_RISK_WEIGHT_RATIO,
AGG1.STD_RISK_WEIGHT_RATIO STD_RISK_WEIGHT_RATIO,
AGG1.B2_STD_RISK_WEIGHT_INDICATOR
B2_STD_RISK_WEIGHT_INDICATOR,
AGG1.SLOTTING_RESIDUAL_MATURITY SLOTTING_RESIDUAL_MATURITY,
AGG1.RWA_CALC_METHOD RWA_CALC_METHOD,
AGG1.LRFE_UFE_FLAG LRFE_UFE_FLAG,
AGG1.OBLIGOR_TYPE OBLIGOR_TYPE,
AGG1.QCCP_FLAG QCCP_FLAG,
AGG1.DOUBLE_DEFAULT_FLAG DOUBLE_DEFAULT_FLAG,
AGG1.TRADING_BOOK_FLAG TRADING_BOOK_FLAG,
AGG1.REPORTING_TYPE_CODE REPORTING_TYPE_CODE,
AGG1.B3_CVA_CC_ADV_FLAG B3_CVA_CC_ADV_FLAG,
AGG1.B2_STD_CCF B2_STD_CCF,
AGG1.B2_STD_CCF_LESS_THAN_YEAR B2_STD_CCF_LESS_THAN_YEAR,
AGG1.B2_STD_CCF_MORE_THAN_YEAR B2_STD_CCF_MORE_THAN_YEAR,
AGG1.B2_IRB_OBSRVD_NEW_DEFAULT_FLAG
   B2_IRB_OBSRVD_NEW_DEFAULT_FLAG,
AGG1.B2_STD_OBSRVD_NEW_DEFAULT_FLAG
   B2_STD_OBSRVD_NEW_DEFAULT_FLAG,
SUM (AGG1.B2_IRB_ORIG_EXP_PRE_CON_FACTOR)
   B2_IRB_ORIG_EXP_PRE_CON_FACTOR,
SUM (AGG1.IRB_ORIG_EXP_PRE_CONV_ONBAL)
   IRB_ORIG_EXP_PRE_CONV_ONBAL,
SUM (AGG1.IRB_ORIG_EXP_PRE_CONV_OFBAL)
   IRB_ORIG_EXP_PRE_CONV_OFBAL,
SUM (AGG1.B2_STD_ORIG_EXP_PRE_CON_FACTOR)
   B2_STD_ORIG_EXP_PRE_CON_FACTOR,
SUM (AGG1.STD_ORIG_EXP_PRE_CONV_ONBAL)
   STD_ORIG_EXP_PRE_CONV_ONBAL,
SUM (AGG1.STD_ORIG_EXP_PRE_CONV_OFBAL)
   STD_ORIG_EXP_PRE_CONV_OFBAL,
SUM (AGG1.B3_CCP_MARGIN_INITL_CASH_AMT)
   B3_CCP_MARGIN_INITL_CASH_AMT,
SUM (AGG1.B3_CCP_MARGIN_INITL_NOCASH_AMT)
   B3_CCP_MARGIN_INITL_NOCASH_AMT,
SUM (AGG1.B3_CVA_PROVISION_AMT) B3_CVA_PROVISION_AMT,
SUM (AGG1.B2_IRB_PROVISIONS_AMT) B2_IRB_PROVISIONS_AMT,
SUM (AGG1.B2_STD_PROVISIONS_AMT) B2_STD_PROVISIONS_AMT,
SUM (AGG1.B2_STD_PROVISIONS_AMT_ONBAL)
   B2_STD_PROVISIONS_AMT_ONBAL,
SUM (AGG1.B2_STD_PROVISIONS_AMT_OFBAL)
   B2_STD_PROVISIONS_AMT_OFBAL,
SUM (AGG1.B2_IRB_CRM_UFCP_GUAR_AMT) B2_IRB_CRM_UFCP_GUAR_AMT,
SUM (AGG1.B2_IRB_CRM_UFCP_CRED_DERIV_AMT)
   B2_IRB_CRM_UFCP_CRED_DERIV_AMT,
SUM (AGG1.B2_IRB_CRM_FCP_ELG_FIN_COL_AMT)
   B2_IRB_CRM_FCP_ELG_FIN_COL_AMT,
SUM (AGG1.B2_IRB_CRM_FCP_OTH_PHY_COL_AMT)
   B2_IRB_CRM_FCP_OTH_PHY_COL_AMT,
SUM (AGG1.B2_IRB_CRM_FCP_OTH_FUNDED_AMT)
   B2_IRB_CRM_FCP_OTH_FUNDED_AMT,
SUM (AGG1.B2_IRB_CRM_FCP_REAL_ESTATE_AMT)
   B2_IRB_CRM_FCP_REAL_ESTATE_AMT,
SUM (AGG1.B2_IRB_CRM_FCP_RECEIVABLES_AMT)
   B2_IRB_CRM_FCP_RECEIVABLES_AMT,
SUM (AGG1.B2_IRB_CRM_UFCP_DOUBLE_DEF_AMT)
   B2_IRB_CRM_UFCP_DOUBLE_DEF_AMT,
SUM (AGG1.B2_STD_EFF_GTEE_AMT) B2_STD_EFF_GTEE_AMT,
SUM (AGG1.B2_STD_EFF_CDS_AMT) B2_STD_EFF_CDS_AMT,
SUM (AGG1.B2_STD_OTH_FUN_CRED_PROT_AMT)
   B2_STD_OTH_FUN_CRED_PROT_AMT,
SUM (AGG1.B2_STD_EFF_FIN_COLL_AMT) B2_STD_EFF_FIN_COLL_AMT,
SUM (AGG1.B2_STD_COLL_VOLATILITY_AMT)
   B2_STD_COLL_VOLATILITY_AMT,
SUM (AGG1.B2_STD_COLL_MTY_MISMATCH_AMT)
   B2_STD_COLL_MTY_MISMATCH_AMT,
SUM (AGG1.B2_IRB_NETTED_COLL_GBP) B2_IRB_NETTED_COLL_GBP,
SUM (AGG1.B2_STD_NETTED_COLL_GBP) B2_STD_NETTED_COLL_GBP,
SUM (AGG1.B2_STD_CRM_TOT_OUTFLOW) B2_STD_CRM_TOT_OUTFLOW,
SUM (AGG1.B2_STD_CRM_TOT_OUTFLOW_ONBAL)
   B2_STD_CRM_TOT_OUTFLOW_ONBAL,
SUM (AGG1.B2_STD_CRM_TOT_OUTFLOW_OFBAL)
   B2_STD_CRM_TOT_OUTFLOW_OFBAL,
SUM (AGG1.B2_STD_CRM_TOT_INFLOW) B2_STD_CRM_TOT_INFLOW,
SUM (AGG1.B2_STD_CRM_TOT_INFLOW_ONBAL)
   B2_STD_CRM_TOT_INFLOW_ONBAL,
SUM (AGG1.B2_STD_CRM_TOT_INFLOW_OFBAL)
   B2_STD_CRM_TOT_INFLOW_OFBAL,
SUM (AGG1.EAD_LGD_NUMERATOR) EAD_LGD_NUMERATOR,
SUM (AGG1.EAD_LGD_NUMERATOR_ON) EAD_LGD_NUMERATOR_ON,
SUM (AGG1.EAD_LGD_NUMERATOR_OFF) EAD_LGD_NUMERATOR_OFF,
SUM (AGG1.EAD_MAT_YEARS_NUMERATOR) EAD_MAT_YEARS_NUMERATOR,
SUM (AGG1.EAD_MAT_YEARS_NUMERATOR_ON)
   EAD_MAT_YEARS_NUMERATOR_ON,
SUM (AGG1.EAD_MAT_YEARS_NUMERATOR_OFF)
   EAD_MAT_YEARS_NUMERATOR_OFF,
SUM (AGG1.EAD_PD_NUMERATOR) EAD_PD_NUMERATOR,
SUM (AGG1.EAD_PD_NUMERATOR_ON) EAD_PD_NUMERATOR_ON,
SUM (AGG1.EAD_PD_NUMERATOR_OFF) EAD_PD_NUMERATOR_OFF,
SUM (AGG1.EAD_POST_CRM_AMT) EAD_POST_CRM_AMT,
SUM (AGG1.B2_IRB_EAD_AMT_ONBAL) B2_IRB_EAD_AMT_ONBAL,
SUM (AGG1.B2_IRB_EAD_AMT_OFBAL) B2_IRB_EAD_AMT_OFBAL,
SUM (AGG1.B2_APP_EXPECTED_LOSS_AMT) B2_APP_EXPECTED_LOSS_AMT,
SUM (AGG1.B2_IRB_EL_AMT_ONBAL) B2_IRB_EL_AMT_ONBAL,
SUM (AGG1.B2_IRB_EL_AMT_OFBAL) B2_IRB_EL_AMT_OFBAL,
SUM (AGG1.RWA_POST_CRM_AMOUNT) RWA_POST_CRM_AMOUNT,
SUM (AGG1.B2_IRB_RWA_AMT_ONBAL) B2_IRB_RWA_AMT_ONBAL,
SUM (AGG1.B2_IRB_RWA_AMT_OFBAL) B2_IRB_RWA_AMT_OFBAL,
SUM (AGG1.B3_CCP_MARGIN_INITL_RWA_AMT)
   B3_CCP_MARGIN_INITL_RWA_AMT,
SUM (AGG1.B3_CCP_MARGIN_NONINITL_RWA_AMT)
   B3_CCP_MARGIN_NONINITL_RWA_AMT,
SUM (AGG1.B1_RWA_POST_CRM_AMT) B1_RWA_POST_CRM_AMT,
SUM (AGG1.CORP_OBLIGOR_COUNT) CORP_OBLIGOR_COUNT,
SUM (AGG1.RETAIL_OBLIGOR_COUNT) RETAIL_OBLIGOR_COUNT,
SUM (AGG1.UNSETTLED_AMOUNT) UNSETTLED_AMOUNT,
SUM (AGG1.UNSETTLED_PRICE_DIFFERENCE_AMT)
   UNSETTLED_PRICE_DIFFERENCE_AMT,
SUM (AGG1.B3_CVA_CC_ADV_VAR_AVG) B3_CVA_CC_ADV_VAR_AVG,
SUM (AGG1.B3_CVA_CC_ADV_VAR_SPOT) B3_CVA_CC_ADV_VAR_SPOT,
SUM (AGG1.B3_CVA_CC_ADV_VAR_USED) B3_CVA_CC_ADV_VAR_USED,
SUM (AGG1.B3_CVA_CC_ADV_VAR_STRESS_AVG)
   B3_CVA_CC_ADV_VAR_STRESS_AVG,
SUM (AGG1.B3_CVA_CC_ADV_VAR_STRESS_SPOT)
   B3_CVA_CC_ADV_VAR_STRESS_SPOT,
SUM (AGG1.B3_CVA_CC_ADV_VAR_STRESS_USED)
   B3_CVA_CC_ADV_VAR_STRESS_USED,
SUM (AGG1.B3_CVA_CC_CREDIT_SPREAD_MEAN)
   B3_CVA_CC_CREDIT_SPREAD_MEAN,
SUM (AGG1.B3_CVA_CC_CDS_SNGL_NM_NTNL_AMT)
   B3_CVA_CC_CDS_SNGL_NM_NTNL_AMT,
SUM (AGG1.B3_CVA_CC_CDS_INDEX_NTNL_AMT)
   B3_CVA_CC_CDS_INDEX_NTNL_AMT,
SUM (AGG1.B3_CVA_CC_CAPITAL_AMT) B3_CVA_CC_CAPITAL_AMT,
SUM (AGG1.B3_CVA_CC_RWA_AMT) B3_CVA_CC_RWA_AMT,
SUM (AGG1.B2_STD_NET_EXP_PRE_CRM_SUBST)
   B2_STD_NET_EXP_PRE_CRM_SUBST,
SUM (AGG1.STD_NET_EXP_PRECRM_SUBST_ONBAL)
   STD_NET_EXP_PRECRM_SUBST_ONBAL,
SUM (AGG1.STD_NET_EXP_PRECRM_SUBST_OFBAL)
   STD_NET_EXP_PRECRM_SUBST_OFBAL,
SUM (AGG1.B2_STD_NET_EXP_POST_CRM_SUBST)
   B2_STD_NET_EXP_POST_CRM_SUBST,
SUM (AGG1.STD_NET_EXP_POSTCRM_SUBT_ONBAL)
   STD_NET_EXP_POSTCRM_SUBT_ONBAL,
SUM (AGG1.STD_NET_EXP_POSTCRM_SUBT_OFBAL)
   STD_NET_EXP_POSTCRM_SUBT_OFBAL,
SUM (AGG1.B2_STD_FULLY_ADJ_EXP) B2_STD_FULLY_ADJ_EXP,
SUM (AGG1.B2_STD_FULLY_ADJ_EXP_ONBAL)
   B2_STD_FULLY_ADJ_EXP_ONBAL,
SUM (AGG1.B2_STD_FULLY_ADJ_EXP_OFBAL)
   B2_STD_FULLY_ADJ_EXP_OFBAL,
SUM (AGG1.B2_STD_FULLY_ADJ_EXP_CCF_0)
   B2_STD_FULLY_ADJ_EXP_CCF_0,
SUM (AGG1.B2_STD_FULLY_ADJ_EXP_CCF_20)
   B2_STD_FULLY_ADJ_EXP_CCF_20,
SUM (AGG1.B2_STD_FULLY_ADJ_EXP_CCF_50)
   B2_STD_FULLY_ADJ_EXP_CCF_50,
SUM (AGG1.B2_STD_FULLY_ADJ_EXP_CCF_100)
   B2_STD_FULLY_ADJ_EXP_CCF_100,
SUM (AGG1.B2_STD_EXPOSURE_VALUE) B2_STD_EXPOSURE_VALUE,
SUM (AGG1.B2_STD_EXPOSURE_VALUE_ONBAL)
   B2_STD_EXPOSURE_VALUE_ONBAL,
SUM (AGG1.B2_STD_EXPOSURE_VALUE_OFBAL)
   B2_STD_EXPOSURE_VALUE_OFBAL,
SUM (AGG1.B2_STD_EAD_POST_CRM_AMT_ONBAL)
   B2_STD_EAD_POST_CRM_AMT_ONBAL,
SUM (AGG1.B2_STD_EAD_POST_CRM_AMT_OFBAL)
   B2_STD_EAD_POST_CRM_AMT_OFBAL,
SUM (AGG1.B2_STD_RWA_AMT) B2_STD_RWA_AMT,
SUM (AGG1.B2_STD_RWA_AMT_ONBAL) B2_STD_RWA_AMT_ONBAL,
SUM (AGG1.B2_STD_RWA_AMT_OFBAL) B2_STD_RWA_AMT_OFBAL,
SUM (AGG1.B2_STD_RWA_POST_CRM_AMT_ONBAL)
   B2_STD_RWA_POST_CRM_AMT_ONBAL,
SUM (AGG1.B2_STD_RWA_POST_CRM_AMT_OFBAL)
   B2_STD_RWA_POST_CRM_AMT_OFBAL,
SUM (AGG1.B2_STD_CRM_TOT_OUTFLOW_RWA)
   B2_STD_CRM_TOT_OUTFLOW_RWA,
SUM (AGG1.B2_STD_CRM_TOT_INFLOW_RWA)
   B2_STD_CRM_TOT_INFLOW_RWA,
SUM (AGG1.IMP_WRITE_OFF_AMT) IMP_WRITE_OFF_AMT,
SUM (AGG1.IMP_IMPAIRMENT_AMT) IMP_IMPAIRMENT_AMT,
SUM (AGG1.B2_STD_COLL_FX_HAIRCUT_AMT)
   B2_STD_COLL_FX_HAIRCUT_AMT,
AGG1.CRD4_REP_IRB_FLAG CRD4_REP_IRB_FLAG,
AGG1.CRD4_REP_IRBEQ_FLAG CRD4_REP_IRBEQ_FLAG,
AGG1.CRD4_REP_STD_FLAG CRD4_REP_STD_FLAG,
AGG1.CRD4_REP_STDFLOW_FLAG CRD4_REP_STDFLOW_FLAG,
AGG1.CRD4_REP_SETTL_FLAG CRD4_REP_SETTL_FLAG,
AGG1.CRD4_REP_CVA_FLAG CRD4_REP_CVA_FLAG,
AGG1.STD_EXP_TYPE_PRI_ORDER_RULE_RK
   STD_EXP_TYPE_PRI_ORDER_RULE_RK,
AGG1.CRD4_SOV_SUBSTITUTION_FLAG CRD4_SOV_SUBSTITUTION_FLAG,
AGG1.STD_RW_PRIORITY_ORDER_RULE_RK
   STD_RW_PRIORITY_ORDER_RULE_RK,
AGG1.UNLIKELY_PAY_FLAG UNLIKELY_PAY_FLAG,
AGG1.RISK_ON_RRU_RK RISK_ON_RRU_RK,
SUM (AGG1.B2_STD_EXP_HAIRCUT_ADJ_AMT)
   B2_STD_EXP_HAIRCUT_ADJ_AMT,
AGG1.COUNTERPARTY_RK COUNTERPARTY_RK,
AGG1.STD_EXPOSURE_DEFAULT_FLAG STD_EXPOSURE_DEFAULT_FLAG,
AGG1.CRD4_STD_RP_SME_FLAG CRD4_STD_RP_SME_FLAG,
AGG1.CRD4_IRB_RP_SME_FLAG CRD4_IRB_RP_SME_FLAG,
AGG1.STD_SME_DISCOUNT_APP_FLAG STD_SME_DISCOUNT_APP_FLAG,
AGG1.IRB_SME_DISCOUNT_APP_FLAG IRB_SME_DISCOUNT_APP_FLAG,
AGG1.TRANSITIONAL_PORTFOLIO_FLAG TRANSITIONAL_PORTFOLIO_FLAG,
AGG1.SLOTTING_EFF_MATURITY_BAND_RK  SLOTTING_EFF_MATURITY_BAND_RK,
AGG1.COREP_IRB_ASSET_CLASS_RK COREP_IRB_ASSET_CLASS_RK,
AGG1.COREP_CRM_REPORTING_FLAG COREP_CRM_REPORTING_FLAG, --R32:JIRA--3506  R1500:29/01/2014:New column added:YADAVRO
SUM (AGG1.ALTERNATIVE_STD_CCF_0), --RANG:JIRA-03699:13-MAR-2014:Added by:SINHSPA
SUM (AGG1.ALTERNATIVE_STD_CCF_20), --RANG:JIRA-03699:13-MAR-2014:Added by:SINHSPA
SUM (AGG1.ALTERNATIVE_STD_CCF_50), --RANG:JIRA-03699:13-MAR-2014:Added by:SINHSPA
SUM (AGG1.ALTERNATIVE_STD_CCF_100), --RANG:JIRA-03699:13-MAR-2014:Added by:SINHSPA
SUM (AGG1.COLL_GOOD_PROV_AMT), --RANG:JIRA-03699:13-MAR-2014:Added by:SINHSPA
AGG1.B2_IRB_INTEREST_AT_DEFAULT_GBP
   B2_IRB_INTEREST_AT_DEFAULT_GBP, -- R33 CR462 NEW COLUMN ADDED
AGG1.PERS_ACC_FLAG PERS_ACC_FLAG,                    --CR527
AGG1.B3_SME_RP_FLAG B3_SME_RP_FLAG,                  --CR527
AGG1.B3_SME_DISCOUNT_FLAG B3_SME_DISCOUNT_FLAG,       --CR527
SUM (AGG1.STATUTORY_LEDGER_BALANCE) STATUTORY_LEDGER_BALANCE ,--R39:R1761:SRIVVIK:Column Added
SUM (AGG1.CARRYING_VALUE) CARRYING_VALUE,--R39:R1756:SRIVVIK:Column Added
SUM (AGG1.LEVERAGE_EXPOSURE) LEVERAGE_EXPOSURE, --R39:R1763:SRIVVIK:Column Added
AGG1.P3_PD_BAND_RK P3_PD_BAND_RK, -- R40:NEW COLUMN FOR PILLAR3 : 13-OCT-2015:GARGSI
SUM (AGG1.EXP_SECURED_BY_COLLATERAL_AMT)
   EXP_SECURED_BY_COLLATERAL_AMT, -- R40:V2.04: New Column PILLAR3 : 07-Nov-2015:Anuj kansal
SUM (AGG1.EXP_SEC_BY_COLL_COVERED_AMT)
   EXP_SEC_BY_COLL_COVERED_AMT, -- R40:V2.04: New Column PILLAR3 : 07-Nov-2015:Anuj kansal
SUM (AGG1.EXP_SECURED_BY_GUARANTEES_AMT)
   EXP_SECURED_BY_GUARANTEES_AMT, -- R40:V2.04: New Column PILLAR3 : 07-Nov-2015:Anuj kansal
SUM (AGG1.EXP_SEC_BY_GUAR_COVERED_AMT)
   EXP_SEC_BY_GUAR_COVERED_AMT, -- R40:V2.04: New Column PILLAR3 : 07-Nov-2015:Anuj kansal
SUM (AGG1.EXP_SECURED_BY_CRD_DRVS_AMT)
   EXP_SECURED_BY_CRD_DRVS_AMT, -- R40:V2.04: New Column PILLAR3 : 07-Nov-2015:Anuj kansal
SUM (AGG1.EXP_SEC_BY_CRD_DRV_COVERED_AMT)
   EXP_SEC_BY_CRD_DRV_COVERED_AMT, -- R40:V2.04: New Column PILLAR3 : 07-Nov-2015:Anuj kansal
AGG1.P3_STD_ASSET_CLASS_RK P3_STD_ASSET_CLASS_RK, --R40:NEW COLUMN FOR PILLAR3 : 10-NOV-2015:GARGSI
SUM (AGG1.BLANK_CRM_CATEGORY_AMT) BLANK_CRM_CATEGORY_AMT, --R40: NEW COLUMN FOR PILLAR3 : 30-OCT-2015:GARGSI
SUM (AGG1.EXP_UNSECURED_CARRYING_AMT)
   EXP_UNSECURED_CARRYING_AMT, -- R40:NEW COLUMN FOR PILLAR3 : 30-OCT-2015:GARGSI
AGG1.CRD4_MEMO_ITEMS_ASSET_CLASS_RK
   CRD4_MEMO_ITEMS_ASSET_CLASS_RK, --R42: Jira RCRRAD 734 : new column added : gargsi : 16-05-2016
SUM (AGG1.INTEREST_SUSPENSE_AMT_GBP)
   INTEREST_SUSPENSE_AMT_GBP,   --R42.1: GARGSI:Column_Added
SUM (AGG1.TOT_REGU_PROV_AMT_GBP) TOT_REGU_PROV_AMT_GBP, --R42.1: GARGSI:Column_Added
AGG1.COREP_INCORP_COUNTRY_RK --R43: NEW COLUMN ADDED:11-07-2016:GARGSI
                            COREP_INCORP_COUNTRY_RK,
SUM (AGG1.NET_MKT_VAL) NET_MKT_VAL, --R43:GARGSI:FOR CCB MART
SUM (AGG1.B2_APP_CAP_REQ_POST_CRM_AMT)
   B2_APP_CAP_REQ_POST_CRM_AMT,    --R43:GARGSI:FOR CCB MART
AGG1.LER_CHILD_COUNTERPARTY_RK --R44:GARGSI:14-12-2016:NEW COLUMN ADDED
                              LER_CHILD_COUNTERPARTY_RK,
AGG1.IG_EXCLUSION_FLAG --R44:GARGSI:14-12-2016:NEW COLUMN ADDED
                      IG_EXCLUSION_FLAG,
AGG1.NEW_IN_DEFAULT_FLAG,             --R44:R1977:ANKITA ROY
AGG1.WALKER_COST_CENTRE_RK,                --R44 R1977 Ankita
AGG1.RETAIL_POOL_SME_FLAG
      RETAIL_POOL_SME_FLAG,     --R44.3--GARGSI:22-02-2017--ADDED: R2023
AGG1.SYS_CODE
       SYS_CODE, --R44.3--GARGSI:22-02-2017--ADDED-R2023
AGG1.CS_PROXY_USED_FLAG CS_PROXY_USED_FLAG, -- R45.2--BHARALI:02-05-2017--ADDED R2056
AGG1.MARKET_RISK_SUB_TYPE
      MARKET_RISK_SUB_TYPE,  --R45.2:CLAYTON:22-05-2017:NEW COLUMN ADDED
----------------------------------------------------------
----R47.1:R2157:GARGSI:13/10/2017:NEW COLUMNS ADDED---START---
-------------------------------------------------------
SUM(AGG1.ACCRUED_INTEREST_GBP) ACCRUED_INTEREST_GBP,
SUM(AGG1.ACCRUED_INT_ONBAL_AMT) ACCRUED_INT_ONBAL_AMT,
SUM(AGG1.B2_IRB_RWA_PRE_CDS) B2_IRB_RWA_PRE_CDS,
AGG1.DEAL_TYPE DEAL_TYPE,
SUM(AGG1.DRAWN_LEDGER_BALANCE) DRAWN_LEDGER_BALANCE,
SUM(AGG1.EAD_PRE_CRM_AMT) EAD_PRE_CRM_AMT,
SUM(AGG1.GROSS_CARRYING_VALUE) GROSS_CARRYING_VALUE,
SUM(AGG1.IMPAIRMENT_LOSS_GBP) IMPAIRMENT_LOSS_GBP,
SUM(AGG1.OFF_BALANCE_EXPOSURE) OFF_BALANCE_EXPOSURE,
SUM(AGG1.OFF_BAL_LED_EXP_GBP_POST_SEC) OFF_BAL_LED_EXP_GBP_POST_SEC,
SUM(AGG1.ON_BALANCE_LEDGER_EXPOSURE) ON_BALANCE_LEDGER_EXPOSURE,
SUM(AGG1.ON_BAL_LED_EXP_GBP_POST_SEC) ON_BAL_LED_EXP_GBP_POST_SEC,
SUM(AGG1.PROVISION_AMOUNT_GBP) PROVISION_AMT_GBP,
SUM(AGG1.RA_AD_EXP) RA_AD_EXP,
SUM(AGG1.UNDRAWN_COMMITMENT_AMT) UNDRAWN_COMMITMENT_AMT,
--------------------------------------------------------
----R47.1:R2157:GARGSI:13/10/2017:NEW COLUMNS ADDED---END---
-------------------------------------------------------
SUM(AGG1.FSA_GROSS_EXPOSURE)FSA_GROSS_EXPOSURE, --R48.1:R2204:Priyasd:Column Added
AGG1.FSA045_PD_BAND_RK FSA045_PD_BAND_RK,--R48.1:R2204:Priyasd:Column Added
AGG1.ULTIMATE_RING_FENCE_PARENT_RK ULTIMATE_RING_FENCE_PARENT_RK,  --r51:gargsi:31/10/2018:new column added
AGG1.STS_SECURITISATION STS_SECURITISATION,                     --R53:R2459:CLAYTON:Column Added
AGG1.STS_SEC_QUAL_CAP_TRTMNT STS_SEC_QUAL_CAP_TRTMNT,           --R53:R2459:CLAYTON:Column Added
AGG1.STS_SEC_APPROACH_CODE STS_SEC_APPROACH_CODE,               --R53:R2459:CLAYTON:Column Added
SUM(AGG1.B3_APP_RWA_INC_CVA_CC_AMT) B3_APP_RWA_INC_CVA_CC_AMT,  --R53:R2459:CLAYTON:Column Added
--R53:TC412:CLAYTON:Added:Start
SUM(AGG1.IFRS9_TOT_REGU_ECL_AMT_GBP) IFRS9_TOT_REGU_ECL_AMT_GBP,
SUM(AGG1.IFRS9_FINAL_ECL_MES_GBP) IFRS9_FINAL_ECL_MES_GBP,
AGG1.IFRS9_FINAL_STAGE IFRS9_FINAL_STAGE,
AGG1.IFRS9_STAGE_3_TYPE IFRS9_STAGE_3_TYPE,
SUM(AGG1.IFRS9_FINAL_IIS_GBP) IFRS9_FINAL_IIS_GBP,
SUM(AGG1.IFRS9_PROV_IMPAIRMENT_AMT_GBP) IFRS9_PROV_IMPAIRMENT_AMT_GBP,
AGG1.IFRS9_ECL_CURRENCY_CODE IFRS9_ECL_CURRENCY_CODE,
SUM(AGG1.IFRS9_PROV_WRITE_OFF_AMT_GBP) IFRS9_PROV_WRITE_OFF_AMT_GBP,
SUM(AGG1.IFRS9_TOT_STATUT_ECL_AMT_GBP) IFRS9_TOT_STATUT_ECL_AMT_GBP,
SUM(AGG1.IFRS9_DISCNT_UNWIND_AMT_GBP) IFRS9_DISCNT_UNWIND_AMT_GBP,
--R53:TC412:CLAYTON:Added:End
AGG1.RISK_TYPE,          --R56:gargsi:13/05/2019:new column added
SUM(AGG1.NGAAP_PROVISION_AMT_GBP) NGAAP_PROVISION_AMT_GBP,   --R59:R2508:clayton:Column Added
SUM(AGG1.REP_PROVISION_AMT_GBP) REP_PROVISION_AMT_GBP,       --R59:R2508:clayton:Column Added
AGG1.REP_PROVISION_TYPE   REP_PROVISION_TYPE,                 --R64:R2557:khoslar:Column Added
AGG1.C33_EXPOSURE_SECTOR,         --R61:R2547:clayton:Column Added
AGG1.FINREP_COUNTERPARTY_SECTOR,  --R61:R2547:clayton:Column Added
AGG1.IAS39_CLASS,                 --R61:R2547:clayton:Column Added
--R70:DC485:clayton:Start
SUM(AGG1.B2_STD_RWA_PRE_SPRT_AMT) B2_STD_RWA_PRE_SPRT_AMT,
SUM(AGG1.B2_STD_RWA_PRE_SPRT_AMT_ONBAL) B2_STD_RWA_PRE_SPRT_AMT_ONBAL,
SUM(AGG1.B2_STD_RWA_PRE_SPRT_AMT_OFBAL) B2_STD_RWA_PRE_SPRT_AMT_OFBAL,
SUM(AGG1.RWA_POST_CRM_PRE_SPRT_AMOUNT) RWA_POST_CRM_PRE_SPRT_AMOUNT,
SUM(AGG1.B2_IRB_RWA_PRE_SPRT_AMT_ONBAL) B2_IRB_RWA_PRE_SPRT_AMT_ONBAL,
SUM(AGG1.B2_IRB_RWA_PRE_SPRT_AMT_OFBAL) B2_IRB_RWA_PRE_SPRT_AMT_OFBAL,
--R70:DC485:clayton:End
AGG1.CRR2_501A_DISCOUNT_FLAG,    --R72:DC495:clayton:Column Added
AGG1.MORTGAGES_FLAG,             --R72:DC497:clayton:Column Added
AGG1.SECURITY_RK,                 --R72.1:TC548:clayton:Column Added
SUM(AGG1.B2_IRB_CRM_COD_AMT),  --R76:R2685:gargsi:added:26/03/2021
SUM(AGG1.B2_IRB_CRM_LIP_AMT),  --R76:R2685:gargsi:added:26/03/2021
AGG1.BASEL_SECURITY_SUB_TYPE,  --R81:TC630:gargsi:added:15/09/2021
AGG1.SYS_PROTECTION_TYPE FROM AGG1 AGG1   GROUP BY AGG1.YEAR_MONTH_RK,
AGG1.RRU_RK,
AGG1.LE_COUNTERPARTY_RK,
AGG1.DIVISION_RK,
AGG1.COREP_PRODUCT_CATEGORY_RK,
AGG1.PRODUCT_RK,
AGG1.COREP_STD_ASSET_CLASS_RK,
AGG1.COREP_PRDEF_STD_ASSET_CLASS_RK,
AGG1.B2_STD_ASSET_CLASS_RK,
AGG1.COUNTERPARTY_MGS_PD_BAND_RK,
AGG1.UNSETTLED_PERIOD_CODE,
AGG1.UNSETTLED_FACTOR_CODE,
AGG1.CBI_PD_BAND_CODE_RK,
AGG1.INCORP_COUNTRY_RK,
AGG1.BRANCH_COUNTRY_RK,
AGG1.RISK_COUNTRY_RK,
AGG1.OP_COUNTRY_RK,
AGG1.MGS_PD_BAND_CODE_RK,
AGG1.RUN_RK,
AGG1.ADJUST_FLAG,
AGG1.REPORTING_REGULATOR_CODE,
AGG1.BASEL_DATA_FLAG,
AGG1.RWA_APPROACH_CODE,
AGG1.ACLM_PRODUCT_TYPE,
AGG1.RETAIL_OFF_BAL_SHEET_FLAG,
AGG1.DEFAULT_FUND_CONTRIB_INDICATOR,
AGG1.FLOW_TYPE,
AGG1.SME_FLAG,
AGG1.INTERNAL_TRANSACTION_FLAG,
AGG1.IRB_RISK_WEIGHT_RATIO,
AGG1.STD_RISK_WEIGHT_RATIO,
AGG1.B2_STD_RISK_WEIGHT_INDICATOR,
AGG1.SLOTTING_RESIDUAL_MATURITY,
AGG1.RWA_CALC_METHOD,
AGG1.LRFE_UFE_FLAG,
AGG1.OBLIGOR_TYPE,
AGG1.QCCP_FLAG,
AGG1.DOUBLE_DEFAULT_FLAG,
AGG1.TRADING_BOOK_FLAG,
AGG1.REPORTING_TYPE_CODE,
AGG1.B3_CVA_CC_ADV_FLAG,
AGG1.B2_STD_CCF,
AGG1.B2_STD_CCF_LESS_THAN_YEAR,
AGG1.B2_STD_CCF_MORE_THAN_YEAR,
AGG1.B2_IRB_OBSRVD_NEW_DEFAULT_FLAG,
AGG1.B2_STD_OBSRVD_NEW_DEFAULT_FLAG,
AGG1.CRD4_REP_IRB_FLAG,
AGG1.CRD4_REP_IRBEQ_FLAG,
AGG1.CRD4_REP_STD_FLAG,
AGG1.CRD4_REP_STDFLOW_FLAG,
AGG1.CRD4_REP_SETTL_FLAG,
AGG1.CRD4_REP_CVA_FLAG,
AGG1.STD_EXP_TYPE_PRI_ORDER_RULE_RK,
AGG1.CRD4_SOV_SUBSTITUTION_FLAG,
AGG1.STD_RW_PRIORITY_ORDER_RULE_RK,
AGG1.UNLIKELY_PAY_FLAG,
AGG1.RISK_ON_RRU_RK,
AGG1.COUNTERPARTY_RK,
AGG1.STD_EXPOSURE_DEFAULT_FLAG,
AGG1.CRD4_STD_RP_SME_FLAG,
AGG1.CRD4_IRB_RP_SME_FLAG,
AGG1.STD_SME_DISCOUNT_APP_FLAG,
AGG1.IRB_SME_DISCOUNT_APP_FLAG,
AGG1.TRANSITIONAL_PORTFOLIO_FLAG,
AGG1.SLOTTING_EFF_MATURITY_BAND_RK ,
AGG1.COREP_IRB_ASSET_CLASS_RK,
AGG1.COREP_CRM_REPORTING_FLAG, --R32:JIRA--3506  R1500:29/01/2014:New column added:YADAVRO
AGG1.B2_IRB_INTEREST_AT_DEFAULT_GBP, -- R33 CR462 NEW COLUMN ADDED                                               ;
AGG1.PERS_ACC_FLAG,                                  --CR527
AGG1.B3_SME_RP_FLAG,                                 --CR527
AGG1.B3_SME_DISCOUNT_FLAG,                           --CR527
AGG1.P3_PD_BAND_RK, --R40: NEW COLUMN FOR PILLAR3 : 13-OCT-2015:GARGSI
AGG1.P3_STD_ASSET_CLASS_RK, --R40:NEW COLUMN FOR PILLAR3 : 10-NOV-2015:GARGSI
AGG1.CRD4_MEMO_ITEMS_ASSET_CLASS_RK, --R42: Jira RCRRAD 734 :new column added : gargsi : 16-05-2016
AGG1.COREP_INCORP_COUNTRY_RK, --R43: NEW COLUMN ADDED:11-07-2016:GARGSI
AGG1.LER_CHILD_COUNTERPARTY_RK, --R44:GARGSI:14-12-2016:NEW COLUMN ADDED
AGG1.IG_EXCLUSION_FLAG, --R44:GARGSI:14-12-2016:NEW COLUMN ADDED
AGG1.NEW_IN_DEFAULT_FLAG,                 --R44:R1977:ANKITA
AGG1.WALKER_COST_CENTRE_RK,                --R44 R1977 Ankita
AGG1.RETAIL_POOL_SME_FLAG,      --R44.3--GARGSI:22-02-2017--ADDED: R2023
AGG1.SYS_CODE,   --R44.3--GARGSI:22-02-2017--ADDED-R2023
AGG1.CS_PROXY_USED_FLAG, -- R45.2--BHARALI:02-05-2017--ADDED R2056
AGG1.MARKET_RISK_SUB_TYPE,  --R45.2:CLAYTON:22-05-2017:NEW COLUMN ADDED
AGG1.DEAL_TYPE,  --R47.1:R2157:GARGSI:13/10/2017:NEW COLUMN ADDED
AGG1.FSA045_PD_BAND_RK,--R48.1:R2204:Priyasd:Column Added
AGG1.ULTIMATE_RING_FENCE_PARENT_RK,  --r51:gargsi:31/10/2018:new column added
AGG1.STS_SECURITISATION,       --R53:R2459:CLAYTON:Column Added
AGG1.STS_SEC_QUAL_CAP_TRTMNT,  --R53:R2459:CLAYTON:Column Added
AGG1.STS_SEC_APPROACH_CODE,    --R53:R2459:CLAYTON:Column Added
AGG1.IFRS9_FINAL_STAGE,        --R53:TC412:CLAYTON:Column Added
AGG1.IFRS9_STAGE_3_TYPE,       --R53:TC412:CLAYTON:Column Added
AGG1.IFRS9_ECL_CURRENCY_CODE,   --R53:TC412:CLAYTON:Column Added
AGG1.RISK_TYPE,           --R56:gargsi:13/05/2019:new column added
AGG1.REP_PROVISION_TYPE,         --R64:R2557:khoslar:Column Added
AGG1.C33_EXPOSURE_SECTOR,         --R61:R2547:clayton:Column Added
AGG1.FINREP_COUNTERPARTY_SECTOR,  --R61:R2547:clayton:Column Added
AGG1.IAS39_CLASS,                 --R61:R2547:clayton:Column Added
AGG1.CRR2_501A_DISCOUNT_FLAG,     --R72:DC495:clayton:Column Added
AGG1.MORTGAGES_FLAG,              --R72:DC497:clayton:Column Added
AGG1.SECURITY_RK,                  --R72.1:TC548:clayton:Column Added
AGG1.BASEL_SECURITY_SUB_TYPE,  --R81:TC630:gargsi:added:15/09/2021
AGG1.SYS_PROTECTION_TYPE  --R81:TC630:gargsi:added:15/09/2021
 ''')
 
 
